name: Publish Release to PyPI

on:
  push:
    tags:
      - "v*" 

jobs:
  release:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev patchelf

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine nuitka

      - name: Build Package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          twine upload dist/*

      - name: Install Runtime Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Standalone Executable with Nuitka
        run: |
          nuitka cidre/cli.py --onefile --standalone --output-dir=build --output-filename=cidre --follow-imports

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            build/cidre
          generate_release_notes: true